import json
from datetime import datetime
from pathlib import Path

try:
    from fpdf import FPDF
except ImportError:
    try:
        from fpdf2 import FPDF
    except ImportError:
        # Fallback dummy class if both fail, to prevent server crash
        class FPDF: 
            def __init__(self, *args, **kwargs): pass
            def add_page(self): pass
            def add_font(self, *args, **kwargs): pass
            def set_font(self, *args, **kwargs): pass
            def cell(self, *args, **kwargs): pass
            def ln(self, *args, **kwargs): pass
            def multi_cell(self, *args, **kwargs): pass
            def line(self, *args, **kwargs): pass
            def output(self, *args): pass
import os

def export_to_markdown(history: list[dict], sources_meta: dict = None) -> str:
    """
    Converts chat history to a formatted Markdown string.
    history: list of {"role": "user"/"bot", "text": "...", "timestamp": "...", "sources": [...]}
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md = f"# AI Chat Export - {now}\n\n"
    md += "---\n\n"

    for msg in history:
        role = "👤 คุณ" if msg.get("role") == "user" else "🤖 ผู้ช่วย AI"
        time = msg.get("timestamp", "")
        content = msg.get("text", "")
        
        md += f"### {role} ({time})\n"
        md += f"{content}\n\n"
        
        # Add sources if available for bot messages
        sources = msg.get("sources", [])
        if sources:
            md += "**เอกสารอ้างอิง:**\n"
            for s in sources:
                md += f"- {s}\n"
            md += "\n"
            
        md += "---\n\n"

    md += "\n*Generated by Organizational AI Chatbot*"
    return md

def export_to_pdf(history: list[dict], folder: Path) -> Path:
    """Converts chat history to a formatted PDF file with Thai support."""
    pdf = FPDF()
    pdf.add_page()
    
    # Detect OS and search for Thai fonts accordingly
    font_paths = []
    if os.name == 'nt': # Windows
        font_paths = [
            r"C:\Windows\Fonts\leelawad.ttf",
            r"C:\Windows\Fonts\thsarabunnew.ttf",
            r"C:\Windows\Fonts\tahoma.ttf",
            r"C:\Windows\Fonts\arial.ttf"
        ]
    else: # Linux/Pi/macOS
        font_paths = [
            "/usr/share/fonts/truetype/thai/THSarabunNew.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansThai-Regular.ttf"
        ]
    
    font_path = None
    for f in font_paths:
        if os.path.exists(f):
            font_path = f
            break
            
    if font_path:
        pdf.add_font("THFont", "", font_path)
        pdf.set_font("THFont", size=12)
    else:
        pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, txt="OrgChat Conversation Export", ln=1, align='C')
    pdf.ln(10)

    for msg in history:
        role = "User" if msg.get("role") == "user" else "AI"
        content = msg.get("text", "")
        sources = msg.get("sources", [])
        
        pdf.set_font(pdf.font_family, 'B' if font_path else '', 11)
        pdf.cell(0, 10, txt=f"{role}:", ln=1)
        
        pdf.set_font(pdf.font_family, '', 10)
        # Handle newlines and multi-cell for content
        pdf.multi_cell(0, 7, txt=content)
        
        if sources:
            pdf.ln(2)
            pdf.set_font(pdf.font_family, 'I' if font_path else '', 8)
            pdf.cell(0, 5, txt=f"Sources: {', '.join(sources)}", ln=1)
            
        pdf.ln(5)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
        pdf.ln(5)

    filename = f"chat_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = folder / filename
    pdf.output(str(file_path))
    return file_path

def save_export_file(content: str, folder: Path, prefix: str = "chat_export") -> Path:
    """Saves the content to a file and returns the path."""
    folder.mkdir(parents=True, exist_ok=True)
    filename = f"{prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    file_path = folder / filename
    file_path.write_text(content, encoding="utf-8")
    return file_path
